# Generated by Django 6.0.3 on 2026-03-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glagroapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sw', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('description_sw', models.TextField()),
                ('description_en', models.TextField()),
                ('usage_time_sw', models.CharField(max_length=200)),
                ('usage_time_en', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='seeds/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
