# Generated by Django 6.0.3 on 2026-03-20 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glagroapp', '0003_seedorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmManagementService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name_sw', models.CharField(max_length=100)),
                ('service_name_en', models.CharField(max_length=100)),
                ('description_sw', models.TextField()),
                ('description_en', models.TextField()),
                ('image', models.ImageField(upload_to='services/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FarmServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=100)),
                ('farmer_phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='glagroapp.farmmanagementservice')),
            ],
        ),
        migrations.CreateModel(
            name='FarmServiceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=100)),
                ('farmer_phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('before_description', models.TextField()),
                ('before_image', models.ImageField(blank=True, null=True, upload_to='farm_reports/before/')),
                ('after_description', models.TextField()),
                ('after_image', models.ImageField(blank=True, null=True, upload_to='farm_reports/after/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='glagroapp.farmmanagementservice')),
            ],
        ),
    ]
