# Generated by Django 6.0.3 on 2026-03-20 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glagroapp', '0004_farmmanagementservice_farmserviceorder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_sw', models.CharField(max_length=150)),
                ('topic_en', models.CharField(max_length=150)),
                ('description_sw', models.TextField()),
                ('description_en', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='consultations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=100)),
                ('farmer_phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('question', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='glagroapp.expertconsultation')),
            ],
        ),
    ]
